let storyA1en = ["The young physics teacher had a late night grading papers and preparing lessons for her sixth grade class, and is having a hard time waking up. She hits the snooze button a few times before dragging herself out of bed and into the shower.",
"Slightly refreshed, she walks into the kitchen, where her grandpa has already made some hot eggy bread for her. The young woman immediately starts complaining to him, saying he shouldn't be up and cooking so early in the morning with his arthritis. To that, the grandpa assures her that he's feeling better and is grateful for his granddaughter's care, but also doesn't want her to starve and leave for work hungry.",
"The young teacher sits down at the kitchen table to check her messages and eat the food. She has a meeting with the principal at 9:30, followed by back-to-back classes all day. One of the classes is a science class and she's planning to conduct a fun experiment on the topic of electricity with her students, she has been preparing all the materials and the instructions beforehand.",
"She's also looking forward to the evening, because she's expecting her grandpa to return from his doctor visit with good news: he seemed to feel better already, and complained about his ankles way less."];
let storyA2en = ["The air alarm blares and the television broadcasts an emergency message. Shock registers on the young woman's face. The grandpa, however, questions the warning's validity. The young teacher quickly contacts her friends for advice. She decides to stay inside and hide in the corridor, far from windows and walls. She packs a bag with essentials, but doesn't plan to leave. ",
"She tries to convince her grandpa to join her, but he remains skeptical and hesitant to leave the kitchen. The young woman tries not to argue, as her grandpa seems nervous. ",
"Going to school today is impossible, as everyone will likely stay home. The young teacher reads through group chat of coworkers and feels like nothing is real anymore. Discussions revolve around war breaking out between two countries. Everyone is either leaving to ensure safety or joining the army to fight intruders."];
let storyA3en = ["As the young woman tries once more to talk sense into her grandpa, the explosive impact of the rocket jolts both of them into action. Debris and shattered glass fly everywhere. The young teacher is hit by a shard, but manages to stay on her feet. Her focus shifts to her grandpa, who is struggling to come to terms with the destruction of their home. The ears of both of them are clogged, deafened by the loud sound of explosion and shattering glass.",
"The two of them make their way to a safer room, the teacher helping her grandpa along the way. She scrolls the flood of the messages in the group chat. She is consumed by thoughts of what they need to pack and how to convince her grandfather to leave the city they both love. The uncertainty and fear of not being able to return home for months weighs heavily on her mind."];

let storyB1en = ["Everyone is awake. The baby is in his crib, cooing and playing with his toys. His young mom is in the kitchen preparing breakfast for her own mother and the baby. Her husband has left to get the missing sour cream and some more groceries at the shop.",
"The grandma is sitting at the kitchen table, sipping her coffee and sharing her throughts on the upcoming celebration of her 60th birthday. She's talking to her daughter about the small family gathering they plan to celebrate the occasion.",
"They're both excited, as they'll finally get a visit from the parents and family of baby's father. This will be the first time for them to see their grandson in person, not just on photos. The grandma and her daughter are discussing the details of the party, such as the guest list, menu, and decorations.",
"In the meanwhile, the young mom is making some pancakes with groundbeef stuffing. She's feeling a bit tired but happy to be starting the day with her loved ones, especially her mom, who came to visit, take care of the newborn baby and celebrate her birthday all the way here from her home village.",
"The young mom will spend her day doing household chores, running errands, and taking care of the baby. Baby's grandma, of course, wants to help too, but her daughter wants her to rest as much as possible to not let that pain in the knees come up and bother her again. Because of that, grandma will probably spend the day watching over the baby and reading some books she brought with her.",
"Baby's dad will leave again right after he comes back home, this time to go to work."];
let storyB2en = ["The women freeze in shock. The baby wails. They've never heard such a warning before.",
"Grandma turns off the stove, gathers essentials. Young mom grabs baby, tries to call husband, no answer. Panic sets in. She tries again and again, no answer. Mother tries to comfort her, but nerves and fear take over.",
"They argue, loudly, as they prepare to flee."];
let storyB3en = ["The kitchen is now a pile of rubble, smoke rising from the debris. The once cozy home is now nothing but twisted metal and broken concrete, with belongings strewn amongst the destruction, which the father, who wasn't at home at the time, has yet to witness."];

let storyC1en = ["Everyone is awake. A little boy is sitting at the kitchen table, eating some sandwiches his mother made for them, and drinking apple juice. He is chattering excitedly about how he spent the day yesterday at the school, telling her about how they played with building blocks and had a contest on who would build the biggest tower. His mother is listening attentively, smiling as she watches him eat.",
"As always, the mom is very happy to hear her son's stories and feels grateful to have this special time with him. She almost forgot how annoyed she felt an hour ago, because of the argument she and her husband had about finances. He left for work right after, so they didn't quite have the chance to finish their discussion, and will have to do it this evening.",
"For now, the mom really just wants to focus on her son and is absorbed in the little fun conversation with him."];
let storyC2en = ["The air alarm blares through the house, jolting the mother and her young son out of their conversation. The television in the kitchen flashes with a message instructing the citizens to take cover. The mother fully expected this turn of events, considering the latest news and what her husband was telling her. She remains calm and quickly begins to follow the instructions.",
"As the mother prepares her son and their house cat for the ride, she can't help but worry about her husband. He made it clear that he was ready to help the local community in every way he can, and didn't see moving away from the country as an option for himself. She tries to push the thoughts out of her mind and focus on getting herself and her son to safety. As she does that, the anger inside of her grows, making her ask why her family have to go through this.",
"Her little boy is confused, but doesn't cry. His mom tells him that they are going to go on a little adventure and that everything will be okay. As he wonders whether his school friends will also go on this adventure, his mom remembers, that the young woman she always asked to babysit his son lives alone in her apartment and has no family in the country, so she might not know where to go or what to do.",
"She quickly calls her up, and luckily the phone gets picked up immediately. Hearing the panic in the girl's voice, the kid's mom quickly decides they will pick her up and bring her to a safe place as well."];
let storyC3en = ["The dishes still on the table from breakfast. The little boy's toys lay scattered on the floor in his room, forgotten in the rush to leave. The windows are shattered. Glass shards cover the floor. The curtains are fluttering in the breeze. Nobody is home."];

let storyD1en = ["The young software developer is sitting at his desk, working on a new project for his company, a simple inventory management tool for a local retail store. He is focused on the task at hand, but his mind keeps drifting to the upcoming deadline and the pressure to make this project a success. He feels sleepy, as he woke up earlier to get more tasks done today.",
"He takes a break and pours himself a cup of coffee, trying to think of ways to wake himself up. His mind wonders to his plans for the weekend. He's been thinking about visiting his parents, but the thought of dealing with the traffic and the crowds makes him hesitant. He wonders if it might be better to just call them instead and catch up on the phone, like he usually does, even if they complain about him not visiting them again.",
"Still feeling undecided, he sits back down at the desk. For now, it's best to just focus on the tasks he's got for today. He takes pride in knowing that his work will help a small business run more efficiently, and wants to do his best."];
let storyD2en = ["The young software developer is in shock as the air alarm goes off. It's the first time something like this has happened, and he's not sure what to do. He stands up from his desk, turns on the TV and stares at it in disbelief, listening.",
"As the message sinks in, he starts to understand what's happening. He's read the news and talked to his friends about the potential conflict escalation between his country and the neighboring country. Anger fills him, as he thinks about how a war has to start again, and especially now, in the midst of an ongoing pandemic.",
"Knowing that everyone will most likely forget about precautions during this chaotic time, he quickly grabs his emergency backpack, filling it with extra masks and antiseptics. After having ensured he packed all of the important documents, he heads out to the nearest safe underground hiding spot he looked for not so long ago, determined to help those in need along his way. He sees a woman struggling with her bags, and he rushes over to assist her, helping her bring them to her car."];
let storyD3en = ["The young software developer's apartment is rocked by the force of the explosion. The windows are blown out, shards of glass littering the floor. The debris from the neighboring house's collapse hits his own home, causing the walls to crack and the ceiling to cave in. Some of the furniture is overturned, personal belongings are scattered on the floor. Nobody is home."];

let storyE1en = ["The teenage girl sits at the edge of her bed, staring at the floor. She has been awake for almost an hour now, but has only now gotten up. She's feeling a mix of emotions, as she recently broke up with her boyfriend from school.",
"She can't help but think about the reason they broke up - he couldn't accept her becoming a vegetarian. He had always been a meat-lover, and he didn't want to change his eating habits for her. He was also mocking her a lot for making her choice, which led to a big argument that ended with them breaking up.",
"Her father, who she lives with, is already up and getting ready for work. She knows he could sense that something was wrong, but she didn't want to talk about it. The last thing she wants to listen to is what her father has to say about it. She fears he will side with the boyfriend on this one, saying her idea is terrible and that she won't keep up with it.",
"The young girl finally gets up to go to the bathroom and brush her teeth. Her mind still wonders to her ex, thinking about how awkward it will be to go to school and see him again. She cringes at the thought of having to talk to him again or even just see him in the hallways. She's not sure if she's ready for that.",
"Her mind still wandering, she walks into the kitchen. Her father is already gone. But he has left her a note on the kitchen table telling her to have a good day at school, with a cute smiley face on it, as usual."];
let storyE2en = ["The teenage girl is still in the kitchen when she hears the air alarm blaring. Initially, she thinks it's just a drill, but as the alarm continues to wail, she realizes something is different. Her heart races as she tries to comprehend the situation.",
"She quickly grabs her phone and sees that she has a missed call from her father. She dials his number back, her hands shaking as she waits for him to answer.",
"When her father picks up, she can hear the panic in his voice. He instructs her to stay home, cover the windows with curtains, pack some food and water into her backpack, grab some blankets and her phone, and sit down in the corridor, far away from any windows or outside-facing walls. He's on his way home.",
"The girl follows her father's instructions, her mind racing with thoughts of what could be happening. She sends a text to her friend, and is surprised to learn that her friend has received similar instructions. As they discuss the possible reasons for the alarm, the girl starts to nervously giggle. \"It must be just a false alarm,\" she thinks to herself, \"there's no way there could be a war starting.\""];
let storyE3en = ["The girl covers her ears, trying to block out the deafening sound of the explosion. She doesn't see what happened but stays in one spot, waiting for her father. She's terrified and doesn't know what to do.",
"As her ears slowly recover from the loud sound, she hears her phone ringing. It's her ex-boyfriend. He's panicked and asking for her help. His father was badly injured by the glass shards and debris flying into the window, and they need all the help they can get moving him to a safe place.",
"The girl is in shock, she wants to go there and help, but understands she needs to wait for her father first. She tells her ex-boyfriend that she'll come as soon as her father arrives home, to try and hold on until then. She wants to help in any way she can. She stares into her phone, waiting for any reassuring message, from anyone: her dad, her ex-boyfriend, her friend."];